using ProudNetSrc.Serialization;

namespace NeoNetsphere.Network.Message.GameRule
{
    public interface IGameRuleMessage
    {
    }

    public class GameRuleMessageFactory : MessageFactory<GameRuleOpCode, IGameRuleMessage>
    {
        public GameRuleMessageFactory()
        {
            // S2C
            Register<RoomEnterPlayerAckMessage>(GameRuleOpCode.RoomEnterPlayerAck);
            Register<RoomLeavePlayerAckMessage>(GameRuleOpCode.RoomLeavePlayerAck);
            Register<RoomLeaveReqeustAckMessage>(GameRuleOpCode.RoomLeaveReqeustAck);
            Register<RoomChangeTeamAckMessage>(GameRuleOpCode.RoomChangeTeamAck);
            Register<RoomChangeTeamFailAckMessage>(GameRuleOpCode.RoomChangeTeamFailAck);
            Register<RoomChoiceTeamChangeAckMessage>(GameRuleOpCode.RoomChoiceTeamChangeAck);
            Register<RoomChoiceTeamChangeFailAckMessage>(GameRuleOpCode.RoomChoiceTeamChangeFailAck);
            Register<GameEventMessageAckMessage>(GameRuleOpCode.GameEventMessageAck);
            Register<GameBriefingInfoAckMessage>(GameRuleOpCode.GameBriefingInfoAck);
            Register<GameChangeStateAckMessage>(GameRuleOpCode.GameChangeStateAck);
            Register<GameChangeSubStateAckMessage>(GameRuleOpCode.GameChangeSubStateAck);
            Register<GameDestroyGameRuleAckMessage>(GameRuleOpCode.GameDestroyGameRuleAck);
            Register<RoomChangeMasterAckMessage>(GameRuleOpCode.RoomChangeMasterAck);
            Register<RoomChangeRefereeAckMessage>(GameRuleOpCode.RoomChangeRefereeAck);
            Register<SlaughterChangeSlaughterAckMessage>(GameRuleOpCode.SlaughterChangeSlaughterAck);
            Register<RoomReadyRoundAckMessage>(GameRuleOpCode.RoomReadyRoundAck);
            Register<RoomBeginRoundAckMessage>(GameRuleOpCode.RoomBeginRoundAck);
            Register<GameAvatarChangeAckMessage>(GameRuleOpCode.GameAvatarChangeAck);
            Register<RoomChangeRuleNotifyAckMessage>(GameRuleOpCode.RoomChangeRuleNotifyAck);
            Register<RoomChangeRuleAckMessage>(GameRuleOpCode.RoomChangeRuleAck);
            Register<RoomChangeRuleFailAckMessage>(GameRuleOpCode.RoomChangeRuleFailAck);
            Register<ScoreMissionScoreAckMessage>(GameRuleOpCode.ScoreMissionScoreAck);
            Register<ScoreKillAckMessage>(GameRuleOpCode.ScoreKillAck);
            Register<ScoreKillAssistAckMessage>(GameRuleOpCode.ScoreKillAssistAck);
            Register<ScoreOffenseAckMessage>(GameRuleOpCode.ScoreOffenseAck);
            Register<ScoreOffenseAssistAckMessage>(GameRuleOpCode.ScoreOffenseAssistAck);
            Register<ScoreDefenseAckMessage>(GameRuleOpCode.ScoreDefenseAck);
            Register<ScoreDefenseAssistAckMessage>(GameRuleOpCode.ScoreDefenseAssistAck);
            Register<ScoreHealAssistAckMessage>(GameRuleOpCode.ScoreHealAssistAck);
            Register<ScoreGoalAckMessage>(GameRuleOpCode.ScoreGoalAck);
            Register<ScoreGoalAssistAckMessage>(GameRuleOpCode.ScoreGoalAssistAck);
            Register<ScoreReboundAckMessage>(GameRuleOpCode.ScoreReboundAck);
            Register<ScoreSuicideAckMessage>(GameRuleOpCode.ScoreSuicideAck);
            Register<ScoreTeamKillAckMessage>(GameRuleOpCode.ScoreTeamKillAck);
            Register<SlaughterRoundWinAckMessage>(GameRuleOpCode.SlaughterRoundWinAck);
            Register<SlaughterSLRoundWinAckMessage>(GameRuleOpCode.SlaughterSLRoundWinAck);
            Register<RoomChangeItemAckMessage>(GameRuleOpCode.RoomChangeItemAck);
            Register<RoomPlayModeChangeAckMessage>(GameRuleOpCode.RoomPlayModeChangeAck);
            Register<GameRefreshGameRuleInfoAckMessage>(GameRuleOpCode.GameRefreshGameRuleInfoAck);
            Register<ArcadeScoreSyncAckMessage>(GameRuleOpCode.ArcadeScoreSyncAck);
            Register<ArcadeBeginRoundAckMessage>(GameRuleOpCode.ArcadeBeginRoundAck);
            Register<ArcadeStageBriefingAckMessage>(GameRuleOpCode.ArcadeStageBriefingAck);
            Register<ArcadeEnablePlayTimeAckMessage>(GameRuleOpCode.ArcadeEnablePlayTimeAck);
            Register<ArcadeStageInfoAckMessage>(GameRuleOpCode.ArcadeStageInfoAck);
            Register<ArcadeRespawnAckMessage>(GameRuleOpCode.ArcadeRespawnAck);
            Register<ArcadeDeathPlayerInfoAckMessage>(GameRuleOpCode.ArcadeDeathPlayerInfoAck);
            Register<ArcadeStageReadyAckMessage>(GameRuleOpCode.ArcadeStageReadyAck);
            Register<ArcadeRespawnFailAckMessage>(GameRuleOpCode.ArcadeRespawnFailAck);
            Register<AdminChangeHPAckMessage>(GameRuleOpCode.AdminChangeHPAck);
            Register<AdminChangeMPAckMessage>(GameRuleOpCode.AdminChangeMPAck);
            Register<ArcadeChangeStageAckMessage>(GameRuleOpCode.ArcadeChangeStageAck);
            Register<ArcadeStageSelectAckMessage>(GameRuleOpCode.ArcadeStageSelectAck);
            Register<ArcadeSaveDateInfoAckMessage>(GameRuleOpCode.ArcadeSaveDateInfoAck);
            Register<SlaughterAttackPointAckMessage>(GameRuleOpCode.SlaughterAttackPointAck);
            Register<SlaughterHealPointAckMessage>(GameRuleOpCode.SlaughterHealPointAck);
            Register<SlaughterChangeBonusTargetAckMessage>(GameRuleOpCode.SlaughterChangeBonusTargetAck);
            Register<ArcadeSucceedLoadingAckMessage>(GameRuleOpCode.ArcadeSucceedLoadingAck);
            Register<MoneyUseCoinAckMessage>(GameRuleOpCode.MoneyUseCoinAck);
            Register<GameLuckyShotAckMessage>(GameRuleOpCode.GameLuckyShotAck);
            Register<FreeAllForChangeTheFirstAckMessage>(GameRuleOpCode.FreeAllForChangeTheFirstAck);
            Register<LogDevLogStartAckMessage>(GameRuleOpCode.LogDevLogStartAck);
            Register<GameKickOutRequestAckMessage>(GameRuleOpCode.GameKickOutRequestAck);
            Register<GameKickOutVoteResultAckMessage>(GameRuleOpCode.GameKickOutVoteResultAck);
            Register<GameKickOutStateAckMessage>(GameRuleOpCode.GameKickOutStateAck);
            Register<CaptainRoundCaptainLifeInfoAckMessage>(GameRuleOpCode.CaptainRoundCaptainLifeInfoAck);
            Register<CaptainSubRoundWinAckMessage>(GameRuleOpCode.CaptainSubRoundWinAck);
            Register<CaptainCurrentRoundInfoAckMessage>(GameRuleOpCode.CaptainCurrentRoundInfoAck);
            Register<SeizeUpdateInfoAckMessage>(GameRuleOpCode.SeizeUpdateInfoAck);
            Register<SeizeUpdateInfoByIntrudeAckMessage>(GameRuleOpCode.SeizeUpdateInfoByIntrudeAck);
            Register<SeizeFeverTimeAckMessage>(GameRuleOpCode.SeizeFeverTimeAck);
            Register<SeizeBuffItemGainAckMessage>(GameRuleOpCode.SeizeBuffItemGainAck);
            Register<SeizeDropBuffItemAckMessage>(GameRuleOpCode.SeizeDropBuffItemAck);
            Register<SeizeUpKeepScoreUpdateAckMessage>(GameRuleOpCode.SeizeUpKeepScoreUpdateAck);
            Register<SeizeUpKeepScoreGetAckMessage>(GameRuleOpCode.SeizeUpKeepScoreGetAck);
            Register<RoomChangeMasterReqeustAckMessage>(GameRuleOpCode.RoomChangeMasterReqeustAck);
            Register<RoomMixedTeamBriefingInfoAckMessage>(GameRuleOpCode.RoomMixedTeamBriefingInfoAck);
            Register<GameEquipCheckAckMessage>(GameRuleOpCode.GameEquipCheckAck);
            Register<RoomGameStartAckMessage>(GameRuleOpCode.RoomGameStartAck);
            Register<RoomGameLoadingAckMessage>(GameRuleOpCode.RoomGameLoadingAck);
            Register<GameTackUpdateAckMessage>(GameRuleOpCode.GameTackUpdateAck);
            Register<RoomGameEndLoadingAckMessage>(GameRuleOpCode.RoomGameEndLoadingAck);
            Register<RoomGamePlayCountDownAckMessage>(GameRuleOpCode.RoomGamePlayCountDownAck);
            Register<InGameItemDropAckMessage>(GameRuleOpCode.InGameItemDropAck);
            Register<InGameItemGetAckMessage>(GameRuleOpCode.InGameItemGetAck);
            Register<InGamePlayerResponseOfDeathAckMessage>(GameRuleOpCode.InGamePlayerResponseOfDeathAck);
            Register<ChallengeRankersAckMessage>(GameRuleOpCode.ChallengeRankersAck);
            Register<ChallengeRankingListAckMessage>(GameRuleOpCode.ChallengeRankingListAck);
            Register<PromotionCouponEventIngameGetAckMessage>(GameRuleOpCode.PromotionCouponEventIngameGetAck);
            Register<RoomEnterPlayerForBookNameTagsAckMessage>(GameRuleOpCode.Room_EnterPlayerForBookNameTags_Ack);
            Register<RoomEnterPlayerInfoListForNameTagAckMessage>(GameRuleOpCode
                .Room_EnterPlayerInfoListForNameTag_Ack);
            Register<RoomChangeRuleNotifyAck2Message>(GameRuleOpCode.Room_ChangeRuleNotify_Ack_2);

            // C2S
            Register<RoomEnterPlayerReqMessage>(GameRuleOpCode.RoomEnterPlayerReq);
            Register<RoomChoiceMasterChangeReqMessage>(GameRuleOpCode.RoomChoiceMasterChangeReq);
            Register<RoomLeaveReguestReqMessage>(GameRuleOpCode.RoomLeaveReguestReq);
            Register<RoomTeamChangeReqMessage>(GameRuleOpCode.RoomTeamChangeReq);
            Register<RoomAutoAssingTeamReqMessage>(GameRuleOpCode.RoomAutoAssingTeamReq);
            Register<RoomAutoMixingTeamReqMessage>(GameRuleOpCode.RoomAutoMixingTeamReq);
            Register<RoomChoiceTeamChangeReqMessage>(GameRuleOpCode.RoomChoiceTeamChangeReq);
            Register<GameEventMessageReqMessage>(GameRuleOpCode.GameEventMessageReq);
            Register<RoomReadyRoundReqMessage>(GameRuleOpCode.RoomReadyRoundReq);
            Register<RoomBeginRoundReqMessage>(GameRuleOpCode.RoomBeginRoundReq);
            Register<GameAvatarDurabilityDecreaseReqMessage>(GameRuleOpCode.GameAvatarDurabilityDecreaseReq);
            Register<GameAvatarChangeReqMessage>(GameRuleOpCode.GameAvatarChangeReq);
            Register<RoomChangeRuleNotifyReqMessage>(GameRuleOpCode.RoomChangeRuleNotifyReq);
            Register<ScoreMissionScoreReqMessage>(GameRuleOpCode.ScoreMissionScoreReq);
            Register<ScoreKillReqMessage>(GameRuleOpCode.ScoreKillReq);
            Register<ScoreKillAssistReqMessage>(GameRuleOpCode.ScoreKillAssistReq);
            Register<ScoreOffenseReqMessage>(GameRuleOpCode.ScoreOffenseReq);
            Register<ScoreOffenseAssistReqMessage>(GameRuleOpCode.ScoreOffenseAssistReq);
            Register<ScoreDefenseReqMessage>(GameRuleOpCode.ScoreDefenseReq);
            Register<ScoreDefenseAssistReqMessage>(GameRuleOpCode.ScoreDefenseAssistReq);
            Register<ScoreHealAssistReqMessage>(GameRuleOpCode.ScoreHealAssistReq);
            Register<ScoreGoalReqMessage>(GameRuleOpCode.ScoreGoalReq);
            Register<ScoreReboundReqMessage>(GameRuleOpCode.ScoreReboundReq);
            Register<ScoreSuicideReqMessage>(GameRuleOpCode.ScoreSuicideReq);
            Register<ScoreTeamKillReqMessage>(GameRuleOpCode.ScoreTeamKillReq);
            Register<RoomItemChangeReqMessage>(GameRuleOpCode.RoomItemChangeReq);
            Register<RoomPlayModeChangeReqMessage>(GameRuleOpCode.RoomPlayModeChangeReq);
            Register<ArcadeScoreSyncReqMessage>(GameRuleOpCode.ArcadeScoreSyncReq);
            Register<ArcadeBeginRoundReqMessage>(GameRuleOpCode.ArcadeBeginRoundReq);
            Register<ArcadeStageClearReqMessage>(GameRuleOpCode.ArcadeStageClearReq);
            Register<ArcadeStageFailedReqMessage>(GameRuleOpCode.ArcadeStageFailedReq);
            Register<ArcadeStageInfoReqMessage>(GameRuleOpCode.ArcadeStageInfoReq);
            Register<ArcadeEnablePlayTimeReqMessage>(GameRuleOpCode.ArcadeEnablePlayTimeReq);
            Register<ArcardRespawnReqMessage>(GameRuleOpCode.ArcardRespawnReq);
            Register<ArcadeStageReadyReqMessage>(GameRuleOpCode.ArcadeStageReadyReq);
            Register<ArcadeStageSelectReqMessage>(GameRuleOpCode.ArcadeStageSelectReq);
            Register<SlaughterAttackPointReqMessage>(GameRuleOpCode.SlaughterAttackPointReq);
            Register<SlaughterHealPointReqMessage>(GameRuleOpCode.SlaughterHealPointReq);
            Register<ArcadeLoagdingSuccessReqMessage>(GameRuleOpCode.ArcadeLoagdingSuccessReq);
            Register<MoneyUseCoinReqMessage>(GameRuleOpCode.MoneyUseCoinReq);
            Register<LogBeginResponeReqMessage>(GameRuleOpCode.LogBeginResponeReq);
            Register<LogWeaponFireReqMessage>(GameRuleOpCode.LogWeaponFireReq);
            Register<GameKickOutRequestReqMessage>(GameRuleOpCode.GameKickOutRequestReq);
            Register<GameKickOutVoteResultReqMessage>(GameRuleOpCode.GameKickOutVoteResultReq);
            Register<InGameItemDropReqMessage>(GameRuleOpCode.InGameItemDropReq);
            Register<InGameItemGetReqMessage>(GameRuleOpCode.InGameItemGetReq);
            Register<InGamePlayerResponseReqMessage>(GameRuleOpCode.InGamePlayerResponseReq);
            Register<RoomIntrudeRoundReqMessage>(GameRuleOpCode.RoomIntrudeRoundReq);
            Register<GameLoadingSuccessReqMessage>(GameRuleOpCode.GameLoadingSuccessReq);
            Register<RoomReadyRoundReq2Message>(GameRuleOpCode.Room_ReadyRound_Req_2);
            Register<RoomBeginRoundReq2Message>(GameRuleOpCode.Room_BeginRound_Req_2);
            Register<RoomIntrudeRoundReq2Message>(GameRuleOpCode.Room_IntrudeRound_Req_2);
            Register<RoomChangeRuleNotifyReq2Message>(GameRuleOpCode.Room_ChangeRuleNotify_Req_2);
        }
    }
}
